# Generated by Django 3.1.5 on 2021-05-05 22:56

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='min_deposit',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=app.models.user_directory_path),
        ),
    ]
